# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d409546787fafc21685713af51668967d59a040e957e9605777c9a359c7ff67b979de261305c704f4432ae2604a7d1bf9084356de1f228188f74e418f55a5e5f

test:
  secret_key_base: 4dbd4a48c896da0fe39537ba73cd578a104952d1153e18efdc408a1644c67832e99ce52ccadc63f00c4ea7d7303ad43315e1da131b765c9894de7148630b1628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
